### PR TITLE
Fix linux file_release detection

### LINKED ISSUE #275: Fedora 35 detected as OracleLinux
I am trying the `os_info` cli on Fedora Linux 35 (which is still in development: due to be released in October).
I ran `cargo install os_info_cli` on Fedora 35 x86_64 and then when I run it:

```ShellSession
$ cargo install os_info_cli
    Updating crates.io index
  Downloaded os_info_cli v1.0.2
  Downloaded 1 crate (7.1 KB) in 2.67s
  Installing os_info_cli v1.0.2
  :
  :
$ os_info 
OS information:
Type: OracleLinux
Version: 35.0.0
Bitness: 64-bit
```
Also here is the os-release contents:
```ShellSession
$ head /etc/os-release 
NAME="Fedora Linux"
VERSION="35 (Workstation Edition Prerelease)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Workstation Edition Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
```
and rust version:
```ShellSession
$ rustc --version
rustc 1.54.0 (Fedora 1.54.0-1.fc35)
```

### LINKED ISSUE #301: Gentoo detected as OracleLinux
when I fire up /usr/bin/cargo -vV on gentoo, it shows the following: 

```
/usr/bin/cargo -Vv
cargo 1.58.0
release: 1.58.0
host: x86_64-gentoo-linux-musl
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1 (sys:0.4.51+curl-7.80.0 system ssl:OpenSSL/1.1.1n)
os: OracleLinux [64-bit]

```

this missdetection happens, as your crate does depend on lsb-release to be installed at runtime to check for a version. Unlinke debian, gentoo doesn't have "real" fixed version numbers since it is a rolling release distro. Therefore, installing lsb-release repeating the command shows: 

```
/usr/bin/cargo -Vv
cargo 1.58.0
release: 1.58.0
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1 (sys:0.4.51+curl-7.80.0 system ssl:OpenSSL/1.1.1n)
os: Linux 2.7 [64-bit]

```

which is a slight improvement, but still not really correct. 

A common practice is to use the version of sys-apps/baselayout as the version number of Gentoo. It ships a simple release file: 

```
cat /etc/gentoo-release
Gentoo Base System release 2.7
``` 
maybe its possible to exploit that file in the future?

### LINKED ISSUE #315: Bug: OracleLinux false detections
I believe I have found how this module has been falsely identifying so many operating systems as OracleLinux. See:
- #301 
- #275 
- [starship/starship#3936](https://github.com/starship/starship/issues/3936)

## Failure Mode
1. `linux/mod.rs` is run
2. `lsb_release` is not installed and fails properly; `linux/mod.rs` falls back to `file_release`
3. Using an array of 6 predefined `DISTRIBUTIONS`, `file_release` will initially attempt to read a `{mariner,centos,fedora,alpine}-release`, each of which fail properly to the next in the array since those files do not exist in this scenario.
4. `file_release` arrives at `os-release` with a fallback Type as `OracleLinux` as defined in `DISTRIBUTIONS`. The `os-release` file DOES exist and a parsing attempt is made.
5. The parser `Matcher::KeyValue` searches for "NAME"
6. **The `get_type` function attempts to convert the identified name string into a `Type`, but fails to match due to not being robust enough: lacking any sort of fuzzy matching or regex, the NAME field not existing, or having a limited list of potential matches.**
7. **With `None` returned by `get_type`, `file_release` uses the fallback Type `OracleLinux`** from the current array element, and proceeds to identify the version as it would any other `os-release`.
8. With a `Type` and `Version` in hand, `file_release` returns, short-circuiting any other array elements defined in `DISTRIBUTIONS` as long as `os-release` exists.
9. The wrong `Type` of `OracleLinux` is returned, while `Version` is correct as it is specific to `os-release` and not the returned `OracleLinux`.

## Notes
- Tests do not cover iteration of the `DISTRIBUTIONS` array but instead skip to using the known correct element, therefore the tests for the 6th element `RedHatEnterprise` cannot uncover the short-circuit caused by the 5th element, `OracleLinux`.
- From what I can tell, inside of `os-release`, the `ID` field is much more stable than `NAME` and is designed to be more script-friendly.
- This structure prevents a `Type` of `Linux` from ever being returned as long as `os-release` exists. That is, many Linux distributions that this module cannot identify specifically, and *should* fallback to just `Linux`, will instead be identified as `OracleLinux` as long as `os-release` exists on the distribution.
  - Note that for #301, Gentoo cannot be identified by `file_release`, so if `lsb_release` is not installed, Gentoo will always be identified as `OracleLinux`. Though, Gentoo has its own specific `gentoo-release` file that should be checked by this crate anyway.

### LINKED ISSUE #316: Bug: matcher has unexpected behavior
`Matcher::KeyValue { key: "ID" }` can match both of these:
```
VERSION_ID="1234"
ID="asdf"
```

It matches the first one it encounters. In this case, it matches `VERSION_ID="1234"`.

## Expected behavior
`Matcher::KeyValue { key: "ID" }` only matches `ID="asdf"` and NOT `VERSION_ID="1234"`. It should match the key exactly.

### PR DESCRIPTION
**Pull request by exincore**
#### Description
Refactors file_release to categorize operating systems from varied release file types more rigorously and with greater programmability. Matcher is no longer a hard dependency, see #176.

Todo:
- [x] Fix Matcher::KeyValue
- [x] Fix Oracle Linux os-release
- [x] Fix inadequate testing

#### Motivation and Context
Fixes Oracle Linux from being detected in almost every case where `lsb_release` is not installed. See #315.

Closes #315 
Closes #316 
Closes #275
Closes #301

### CODE REVIEW

File: os_info/src/linux/file_release.rs [hunk 1]
```diff
@@ -31,100 +31,158 @@ fn retrieve(distributions: &[ReleaseInfo]) -> Option<Info> {
...
+#[derive(Clone)]
 struct ReleaseInfo<'a> {
-    os_type: Type,
+    // The release file the struct corresponds to
     path: &'a str,
-    version_matcher: Matcher,
+    // Outputs the os type given the release file
+    os_type: for<'b> fn(&'b str) -> Option<Type>,
+    // Outputs the os version given the release file
+    version: for<'b> fn(&'b str) -> Option<Version>,
```
Comment (exincore) [inline os_info/src/linux/file_release.rs:62]: Could use more clarification for how function pointers work, especially with lifetimes.

**Review by stanislav-tkach — APPROVED** [review]
Sorry for the late replay and thank you for the great effort!
